[package]
name = "wgduck"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19.1"
nalgebra-glm = "0.18.0"
bytemuck = { version = "1.13.0", features = [ "derive" ] }
ordered-float = "3.4.0"
itertools = "0.11.0"
winit = "0.29.10"